name: Deploy Platform

on:
  push:
    branches: [main]
    paths:
      - 'platform/**'
  workflow_dispatch:

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: platform/admin-worker
        run: npm install
        
      - name: Deploy Admin Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: platform/admin-worker
